### ISSUE TITLE
Kanban board ⛵ Setup and task Delegation.

### ISSUE THREAD

**Issue by gisachris** [ab-noori/EduPlanner-Backend#15]
## Note
**This team comprises of 3 developers @gisachris, @ab-noori, @BANCUNGUYE66 as we take on the Microverse full stack capstone project**

## Link to project
Link to project: [check here !](https://github.com/users/ab-noori/projects/12)

## ScreenShot
![screenshot-github com-2023 09 28-20_14_24](https://github.com/ab-noori/EduPlanner-Backend/assets/125574259/ac62e9d1-7816-497c-b31c-988240bd3eec)

**Comment by Meltrust** [comment]
Hi @ab-noori,

## Wow, you did it 🎉 
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ab-noori** [comment]
**Hi @Meltrust 👋,**
Thank you so much 🙏 for reviewing and approving our project.

![thank-you-gif-22](https://github.com/ab-noori/bookstore-cms/assets/111179533/0848000e-52ce-440c-a114-6c7f859a0eaa)
